apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: opendatahub3
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    # this is required for gpu notebooks
    - kustomizeConfig:
      repoRef:
        name: manifests
        path: radanalyticsio/spark/cluster
      name: radanalyticsio-spark-cluster
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: modified
          path: jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - cuda-11.0.3
        repoRef:
          name: modified 
          path: notebook-images
      name: notebook-images
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.0.9'
    - name: modified
      uri: 'https://github.com/dmarcus-wire/odh-jh-nb/tarball/main'