apiVersion: v1
kind: List
items:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      component.opendatahub.io/name: jupyterhub
      opendatahub.io/component: 'true'
      opendatahub.io/notebook-image: 'true'
    annotations:
      opendatahub.io/notebook-image-url: "https://github.com/thoth-station/s2i-minimal-notebook"
      opendatahub.io/notebook-image-name: "CUDA"
      opendatahub.io/notebook-image-desc: "Jupyter notebook image with GPU support and minimal dependency set to start experimenting with Jupyter environment."
    name: "jupyter-cuda"
  spec:
    lookupPolicy:
      local: true
    tags:
    - annotations:
        opendatahub.io/notebook-software: '[{"name":"Python","version":"v3.8.3"},{"name":"CUDA","version":"11.0.3"}]'
        opendatahub.io/notebook-python-dependencies: '[{"name":"JupyterLab","version":"3.0.14"},{"name":"Notebook","version":"6.3.0"}]'
      name: "py3.8-ubi8-cuda11.0.3"
      referencePolicy:
        type: Local
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: jupyter-cuda-py3.8-ubi8-cuda11.0.3
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: 'jupyter-cuda:py3.8-ubi8-cuda11.0.3'
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: 'python-cuda:3.8-ubi8-cuda11.0.3'
        noCache: true
        dockerfilePath: Dockerfile
    source:
      type: Git
      git:
        ref: python38
        uri: 'https://github.com/thoth-station/s2i-minimal-notebook'
    triggers:
      - type: ConfigChange
      - type: ImageChange
    resources:
      limits:
        memory: 6Gi
      requests:
        memory: 6Gi

